### ISSUE TITLE
keys and push on reference is experimental

### ISSUE THREAD

**Issue by eserte** [pdl/Articulate#32]
The test suite fails for perl >= 5.20 and <= 5.12.
See http://matrix.cpantesters.org/?dist=Articulate

**Comment by pdl** [comment]
Thanks! I'm just installing 5.20.2 now so I can see if there are any other cases before I fix and do a new release.

For the record, my intention is not to use autoderef in any situation.

**Comment by pdl** [comment]
Fixed in v0.002, but a different issue (#33) is preventing installation on 5.12 and below.
